feat/submitter allow retry flag
XGovFormBuilder/digital-form-builder pull request #1134
Opened 2023-11-07 15:17 UTC by ziggy-cyb

# Description

In some instances, it's necessary that a webhook only be tried once in the case that it fails. This feature upgrades the form runner and submitter to accept an `allowRetry` flag, set to `true` or `false`, which determines whether the webhook should be tried more than once.

- Updated `model/schema/schema.ts` to allow `allowRetry` on webhook outputConfiguration.
- Updated queue-model schema to include a column for `allow_retry`
- Updated runner queueService and queueStatusService to pass through the value of `allowRetry` if it's set on the output, or defaults to `true` if not
- Updated submitter to filter out submissions with errors and allow_retry set to false

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce
the testing if necessary.

- [X] Manual testing with attached form jsons

# Checklist:

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation and versioning
- [X] I have updated the architecture diagrams as per Contribute.md OR added an architectural decision record entry

2023-11-07 16:02 UTC, jenbutongit requested changes

2023-11-07 18:24 UTC, ziggy-cyb commented on runner/src/server/services/queueService.ts
>        webhook_url: url ?? null,
ah yeah, I think initially I was thinking every form would put a line in the db and only wanted the ones that have a webhook url to be processed, but you're right we only push in submissions that have webhook urls

2023-11-08 09:37 UTC, jenbutongit requested changes

2023-11-08 09:37 UTC, jenbutongit commented on queue-model/migrations/20231107201153_webhook_url_required/migration.sql
> +  - Made the column `webhook_url` on table `Submission` required. This step will fail if there are existing NULL values in that column.
mind addressing this warning as well please. default empty string is fine

2023-11-08 15:42 UTC, jenbutongit approved these changes

2023-11-09 14:38 UTC, merged