Feature/139 govuk react jsx components
XGovFormBuilder/digital-form-builder pull request #142
Opened 2020-10-05 15:46 UTC by bertrandmc

# Description

- Replace temporary govuk components replicas with components from govuk-react-jsx library.
- Fix broken tests.
- Significant refactor of tests to improve code readability.

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have run all unit tests
- [X] I have manually tested the application and related features

# Checklist:

- [X] My changes do not introduce any new linting errors 
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I have rebased onto master and there are no code conflicts

2020-10-06 10:20 UTC, jenbutongit commented on designer/client/conditions/select-conditions.js
> +    const { data, hints = [] } = this.props
I discovered default destructure syntax recently.. very neat :D

2020-10-06 11:46 UTC, jenbutongit requested changes

2020-10-06 15:47 UTC, bertrandmc commented on designer/client/conditions/select-conditions.js
> +              )} */}
Ooops, cleaned. Thanks.

2020-10-07 09:12 UTC, jenbutongit requested changes

2020-10-07 09:12 UTC, jenbutongit commented on .yarn/build-state.yml
> +# Warning: This file is automatically generated. Removing it is fine, but will
delete please

2020-10-07 09:13 UTC, jenbutongit commented
lgtm apart from build-state. could you delete and add to gitignore please

2020-10-07 09:20 UTC, jenbutongit approved these changes

2020-10-07 09:24 UTC, merged