created an anchor run job that creates and runs a docker image which …
XGovFormBuilder/digital-form-builder pull request #399
Opened 2021-02-18 10:35 UTC by endamccormack

…is anchor tested

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Please also include any acceptance criteria if you have any.

- Change A
- Change B

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce
the testing if necessary.

Before PR's can be merged they will need to be tested by QA and approved where
applicable. To flag the change to QA assign **@XGovFormBuilder/qa** as one of the reviewers.

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My changes do not introduce any new linting errors
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and versioning
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have rebased onto master and there are no code conflicts
- [ ] I have checked deployments are working in all environments
- [ ] I have updated the architecture diagrams as per Contribute.md

2021-02-25 09:41 UTC, TheSpartan1980 approved these changes

2021-02-26 09:43 UTC, jenbutongit requested changes

2021-02-26 09:43 UTC, jenbutongit commented on .github/workflows/anchore-scan.yml
> +      - feature/FORMS-206-add-anchore-scans
are anchore scans ok on your branch? if so, pls remove this line

2021-02-26 09:43 UTC, jenbutongit commented on runner/package.json
> +    "node-sass": "^5.0.0",
w00t

2021-02-26 10:07 UTC, jenbutongit approved these changes

2021-02-26 10:39 UTC, merged