Fix for list based components not getting saved if no list
XGovFormBuilder/digital-form-builder pull request #442
Opened 2021-03-11 16:40 UTC by kakanisridhar

# Description
List based components require a list to be present before saving

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [ ] Manual Testing

# Checklist:

- [X] My changes do not introduce any new linting errors
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and versioning
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] I have rebased onto master and there are no code conflicts
- [ ] I have checked deployments are working in all environments
- [ ] I have updated the architecture diagrams as per Contribute.md

2021-03-15 12:38 UTC, jenbutongit requested changes

2021-03-15 12:38 UTC, jenbutongit commented on designer/client/reducers/component/componentReducer.validations.ts
> +  ) {
you can use optional chaining + nullish coalesce to clean this up
```suggestion
  if ( component?.values?.list ?? false ) 
```
so if component.values is nullish (undefined or null), treat `component?.values?.list` to be false. 

you can do this also, `component?.values?.list === "-1"`

2021-03-15 16:54 UTC, jenbutongit submitted a review, later dismissed

2021-03-29 12:08 UTC, closed without merging

2021-03-29 12:08 UTC, kakanisridhar commented
no longer required