updating readme for test coverage threshold
XGovFormBuilder/digital-form-builder pull request #449
Opened 2021-03-24 11:45 UTC by kakanisridhar

# Description

updating readme for test coverage threshold

## Type of change

Please delete options that are not relevant.

- [X ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [ ] Manual Test

# Checklist:

- [ ] My changes do not introduce any new linting errors
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and versioning
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have rebased onto master and there are no code conflicts
- [ ] I have checked deployments are working in all environments
- [ ] I have updated the architecture diagrams as per Contribute.md

2021-03-24 13:35 UTC, gautampachnandahmo requested changes

2021-03-24 13:35 UTC, gautampachnandahmo commented on runner/README.md
>  Currently CI is done with [circleCI](https://circleci.com). Pushes to master
References to circle CI are wrong

2021-03-24 16:38 UTC, gautampachnandahmo reviewed
Looks good to me. Please get a QA review and demo for the team

2021-03-25 10:02 UTC, TheSpartan1980 approved these changes

2021-03-25 10:03 UTC, TheSpartan1980 commented
@kakanisridhar please complete the PR template

2021-03-25 11:32 UTC, gautampachnandahmo approved these changes

2021-03-25 11:33 UTC, merged