removing next-version 3.0 and fix dispatch
XGovFormBuilder/digital-form-builder pull request #557
Opened 2021-05-20 10:30 UTC by jenbutongit

# Description

as per #555, removing the next-version: 3.0 line

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce
the testing if necessary.

Before PR's can be merged they will need to be tested by QA and approved where
applicable. To flag the change to QA assign **@XGovFormBuilder/qa** as one of the reviewers.

n/a

# Checklist:

- [x] My changes do not introduce any new linting errors
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation and versioning
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have rebased onto main and there are no code conflicts
- [n/a] I have checked deployments are working in all environments
- [n/a] I have updated the architecture diagrams as per Contribute.md

2021-05-20 13:01 UTC, endamccormack approved these changes
⭐ ⭐  are the eye's of the face

2021-05-20 21:36 UTC, endamccormack approved these changes

2021-05-21 08:53 UTC, gstevenson requested changes

2021-05-21 08:53 UTC, gstevenson commented on .github/workflows/notify-external-repositories.yml
>          GITHUB_TOKEN: ${{ secrets.GHCR_PAT }}
```suggestion
        GITHUB_TOKEN: ${{ secrets.GHP_HO_GHCR }}
```

2021-05-21 08:53 UTC, gstevenson commented on .github/workflows/notify-external-repositories.yml
>          GITHUB_TOKEN: ${{ secrets.GHCR_PAT }}
New secret has been added - if we go with this I'll delete the GHCR_PAT secret

2021-05-21 09:00 UTC, gstevenson approved these changes

2021-05-21 10:26 UTC, merged