Draft: Fix/remove moment
XGovFormBuilder/digital-form-builder pull request #763
Opened 2022-02-22 15:36 UTC by adamdavies1

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Please also include any acceptance criteria if you have any.

- Change A
- Change B

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce
the testing if necessary.

Before PR's can be merged they will need to be tested by QA and approved where
applicable. To flag the change to QA assign **@XGovFormBuilder/qa** as one of the reviewers.

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My changes do not introduce any new linting errors
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and versioning
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have rebased onto main and there are no code conflicts
- [ ] I have checked deployments are working in all environments
- [ ] I have updated the architecture diagrams as per Contribute.md

2022-03-10 08:49 UTC, endamccormack approved these changes
looks good to me, worth @jenbutongit having a look before merge

2022-03-23 18:21 UTC, jenbutongit requested changes

2022-03-24 13:37 UTC, adamdavies1 commented on runner/src/server/plugins/engine/components/DateTimePartsField.ts
> +      payload[`${name}__month`],
for this screenshot i put in the date 17/06/1992 11:11. Says its june so it appears to be working
![image](https://user-images.githubusercontent.com/97108643/159928113-61765924-f179-4c54-a070-9eb9ac0944fd.png)

2022-03-24 13:41 UTC, adamdavies1 commented
Putting this back in draft as I think i have found a bug

2022-03-25 16:35 UTC, jenbutongit approved these changes
thanks! 💪

2022-03-25 16:47 UTC, merged