DRAFT: App dependencies update
XGovFormBuilder/digital-form-builder pull request #768
Opened 2022-03-03 11:20 UTC by adamdavies1

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Please also include any acceptance criteria if you have any.

- Change A
- Change B

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce
the testing if necessary.

Before PR's can be merged they will need to be tested by QA and approved where
applicable. To flag the change to QA assign **@XGovFormBuilder/qa** as one of the reviewers.

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My changes do not introduce any new linting errors
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and versioning
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have rebased onto main and there are no code conflicts
- [ ] I have checked deployments are working in all environments
- [ ] I have updated the architecture diagrams as per Contribute.md

2022-03-09 16:11 UTC, adamdavies1 commented
[Designer Failed Packages update List.docx](https://github.com/XGovFormBuilder/digital-form-builder/files/8216270/Designer.Failed.Packages.update.List.docx)
[Model failed packages.docx](https://github.com/XGovFormBuilder/digital-form-builder/files/8216272/Model.failed.packages.docx)

2022-03-23 16:23 UTC, jenbutongit requested changes
just checking to see if this

2022-03-23 16:39 UTC, adamdavies1 commented on .github/workflows/branch--lint-unit-and-smoke-test.yml
> +      - "docs/**"
Just changed this back, it hasnt triggered the build

2022-03-24 11:21 UTC, adamdavies1 commented on .github/workflows/main--lint-unit-build-and-publish-images.yml
> -      - name: Docker layer caching
This is in place to fix the pipeline cache when it fills up and causes a out of memory failure

2022-03-24 11:21 UTC, adamdavies1 commented on docker-compose.yml
> +      cache_from:
This is in place to fix the pipeline cache when it fills up and causes a out of memory failure

2022-03-24 11:21 UTC, adamdavies1 commented on smoke-tests/designer/wdio.conf.js
> +  chrome: { version: "98.0.4758.102" }, // https://chromedriver.chromium.org/
fixes chrome driver out of date error

2022-03-25 16:43 UTC, jenbutongit approved these changes

2022-03-25 17:08 UTC, jenbutongit commented
@adamdavies1 - on smoke tests.. don't worry. I'm moving those over to cypress anyway (see #703)

2022-03-25 17:09 UTC, jenbutongit requested changes
LGTM - I think it needs a conflict resolve though

2022-03-25 18:00 UTC, jenbutongit approved these changes

2022-03-25 18:00 UTC, merged